# version: 0.0
# os: linux

files:             
  - source: Recipe_Management_System.war
    #/webapp/Recipe_Management_System/target/Recipe_Management_System.war
    # destination: /opt/tomcat/webapps
    destination: /usr/share/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./codedeploy/applicationStart.sh
     timeout: 180
     runas: centos
  BeforeInstall:
   - location: ./codedeploy/beforeInstall.sh
     timeout: 180
     runas: centos  
  ApplicationStop:
   - location: ./codedeploy/applicationStop.sh
     timeout: 180
     runas: centos