version: 2
jobs:
  build:
    working_directory: ~/webapp
    filters:
      branches:
        only:
          - assignment7
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #checkout source code to working directory
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip
            # sudo apt-get install -y python3-pip
            sudo pip install awscli
      - run:
          name: Build WAR
          command: |
            pwd
            cd webapp/Recipe_Management_System
            pwd
            ls -al
            ./mvnw clean package
            pwd
            ls -al
            ls -al target/
      - run:
          name: Check War Path
          command: |
            pwd
            cd webapp/Recipe_Management_System
            pwd
            ls -al
            cd target
            pwd
            ls -al    
      - run:
          name: Build Deployment Artifact
          command: |
            pwd
            ls -al
            mkdir codedeploy_artifact
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip /webapp/Recipe_Management_System/target/Recipe_Management_System.war codedeploy/*.sh appspec.yml
            pwd
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            ${AWS_ACCESS_KEY_ID} \
            --profile default
      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            ${AWS_SECRET_ACCESS_KEY} \
            --profile default
      - run:
          name: Configure AWS region
          command: |
            aws configure set region ${AWS_REGION} \
            --profile default      
      - run:
          name: Copy Artifact to S3
          command: aws s3 cp codedeploy_artifact/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${S3_CODEDEPLOY_BUCKET}/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: CodeDeploy API call
          command: |
            aws deploy create-deployment \
              --application-name ${CODEDEPLOY_APPLICATION_NAME} \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name ${CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME} \
              --description "CSYE6225 - CodeDeploy" \
              --s3-location bucket=${S3_CODEDEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
              --region us-east-1 \
              --output json          
      
